### ISSUE TITLE
Arachne regression: ironing_inset does not work

### ISSUE THREAD

**Issue by richfelker** [Ultimaker/CuraEngine#1496]
Using CuraEngine 4.10, ironing_inset works as expected. With Arachne, the ironing toolpath runs all the way to the edge of the surface, producing jagged edges that require significant manual cleanup with a knife or deburring tool.

**Comment by richfelker** [comment]
OK, reading the source, it looks like this issue is related to the bug fixed in https://github.com/Ultimaker/CuraEngine/issues/1265. In particular, the same calculation for a width scale is used, neglecting the possibility that `infill_sparse_thickness` is less than `layer_height` (which is the default in `fdmprinter.def.json`):

https://github.com/Ultimaker/CuraEngine/blob/d7f2d305a02ef52303c85e8942ef4efef90fcf23/src/TopSurface.cpp#L67

The correction here may not even be correct in other cases, though.

**Comment by richfelker** [comment]
Actually, even with that compensated for, or with the inset amount turned way up, the toolpath still goes all the way to the edge. So it looks to me like there's a bug somewhere else too.

**Comment by Ghostkeeper** [comment]
https://github.com/Ultimaker/CuraEngine/pull/1272 was merged to master and it's not currently broken in Master. So I think that was only sideways related at best, but the real issue is still in the changes we made for Arachne somewhere.

**Comment by Ghostkeeper** [comment]
Developers, see issue CURA-8569.

**Comment by richfelker** [comment]
Ping. Is this still broken? I see a potentially related change in 95635c2897 for CURA-8615.

**Comment by Ghostkeeper** [comment]
I'm afraid it is. I tested it by loading in a simple cube and setting the ironing inset to 3mm to make it visible. But the inset wasn't applied to the ironed area.

Our ticket CURA-8569 is still open. It's marked as a must-have for 5.0. The change you pointed out was to fix combing through the ironed area. The travel moves were sometimes mistakenly thinking that they were moving outside of the part instead of on top of the part.
