### ISSUE TITLE
change temperature between the first and second layers

### ISSUE THREAD

**Issue by cicciom** [Ultimaker/CuraEngine#402]
it would be possible to implement a system like all other slicer to set different temperatures between the first and the second layer?

**Comment by BagelOrb** [comment]
Why would you want a different extrusion temperature on the first layer?

Op 19 okt. 2016 09:48 schreef "cicciom" <notifications@github.com>:

**Comment by BagelOrb** [comment]
Would you want a higher or lower temperature?

Op 19 okt. 2016 09:52 schreef :

**Comment by cicciom** [comment]
I have a membership platform on the glass bed without lacquer, where to join the PLA needs a temperature around 210 ° (the first layer) while others print layer I would set the type to 190-200 ° and I have to do it or manually, by acting on the generated gcode, or from the display. since all the other slicer you have this option you could also implement it you please?

**Comment by BagelOrb** [comment]
Ok. I'd like to do this because it's very easy to implement and it will probably help more people than you alone.

If there's any other slicing options Cura is missing, please file new issue reports. We don't have a full overview of what other slicers are doing...

**Comment by BagelOrb** [comment]
BTW: what's a membership platform?!?!

**Comment by cicciom** [comment]
this platform is called gekofeet I would not want to advertise commercial products but does not need any of the heating plate and lacquer, and for me it is excellent as a solution there is also a discussion forum in http://forums.reprap.org/read .php? 363.642683, page = 1.

thanks to the availability.

It will also be available in repetier host?

**Comment by BagelOrb** [comment]
Repetier Host has their own agenda. I don't know whether they're up to date, but I imagine they are lacking behind quite a bit.

**Comment by cicciom** [comment]
It is to be able to use the latest version of your windows without repetier how?

**Comment by Ghostkeeper** [comment]
You can also do this with the "Tweak at Z" post-processing script. It's a little hidden though:

Go into Extensions -> Post-processing -> Modify g-code. Then add a Tweak at Z script. Set the trigger to Layer Nr, set the layer number to 2, and modify the temperature to your liking.

**Comment by cicciom** [comment]
but it is a separate script which is imported into repetier host?

**Comment by Ghostkeeper** [comment]
No, the Tweak at Z script is only for Cura's front-end.

**Comment by cicciom** [comment]
ok, but I think that having this in the curaengine source which then can be used with all systems I think might be better as a solution

**Comment by BagelOrb** [comment]
Fixed in Cura 2.4

**Comment by VanessaE** [comment]
Please re-open this, it is NOT fixed, as not only do different filaments need different temperatures, one needs to fine-tune that first layer temperature properly per-filament if the bed has something like PEI or Printbite on it.

**Comment by VanessaE** [comment]
Done.  #796
